/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#46464b',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f0f1f1',
        outline: '#76777b',
        'outline-variant': '#c7c6cb',
        'surface-tint': '#5e5e62',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1b1b1f',
        'on-primary-container': '#848387',
        'inverse-primary': '#c7c6ca',
        secondary: '#566500',
        'on-secondary': '#ffffff',
        'secondary-container': '#d3ef51',
        'on-secondary-container': '#5b6b00',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#141e18',
        'on-tertiary-container': '#7c867f',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e3e2e6',
        'primary-fixed-dim': '#c7c6ca',
        'on-primary-fixed': '#1b1b1f',
        'on-primary-fixed-variant': '#46464a',
        'secondary-fixed': '#d3ef51',
        'secondary-fixed-dim': '#b8d236',
        'on-secondary-fixed': '#181e00',
        'on-secondary-fixed-variant': '#404c00',
        'tertiary-fixed': '#dae5dc',
        'tertiary-fixed-dim': '#bec9c1',
        'on-tertiary-fixed': '#141e18',
        'on-tertiary-fixed-variant': '#3f4943',
        background: '#a1aca4', // "Atmospheric Outer Canvas"
        'on-background': '#1a1c1c',
        'surface-variant': '#e2e2e2',
        // Tactile Modernist custom colors
        'matte-charcoal': '#121316',
        'matte-charcoal-light': '#18191c',
        'matte-charcoal-lighter': '#1c1e22',
        'chartreuse': '#d6f254',
        'chartreuse-light': '#e8fa8c',
        'porcelain': '#fbfbfb',
        'sage-slate': '#a1aca4',
        'sage-tint': '#8d9990',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        'sm': '0.5rem',
        DEFAULT: '1rem',
        'md': '1.5rem',
        'lg': '2rem',
        'xl': '3rem',
        '3xl': '2rem', // for 32px
        'full': '9999px',
      },
      spacing: {
        gutter: '1.25rem',
        'gutter-desktop': '1.5rem',
        margin: '0.75rem',
        'margin-desktop': '1.25rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.875rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
      },
      boxShadow: {
        'low-elevation': '0 20px 48px -12px rgba(18, 19, 22, 0.14), 0 1px 2px rgba(18, 19, 22, 0.04)',
        'nested-card': '0 2px 8px rgba(18, 19, 22, 0.03)',
        'charcoal-dock': '0 16px 36px -6px rgba(0, 0, 0, 0.35), inset 0 0 0 1px rgba(255, 255, 255, 0.06)',
        'chartreuse-glow': '0 0 20px rgba(214, 242, 84, 0.38)',
      }
    },
  },
  plugins: [],
}
